# Faulty program, infinite loop

number = 1
while number<5:
    print(number)

# This part is never reached:
print("All ready.")